/*
 * SPDX-FileCopyrightText: Copyright (c) 2024-2026, NVIDIA CORPORATION.
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * NOTE: this file is generated by compute_distance_00_generate.py
 *
 * Make changes there and run in this directory:
 *
 * > python compute_distance_00_generate.py
 *
 */

#include "compute_distance_binary_adc-impl.cuh"

namespace cuvs::neighbors::cagra::detail {

using namespace cuvs::distance;
template struct binary_adc_descriptor_spec<16, 256, float, uint32_t, float>;

}  // namespace cuvs::neighbors::cagra::detail
