/*
 * SPDX-FileCopyrightText: Copyright (c) 2023-2026, NVIDIA CORPORATION.
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * NOTE: this file is generated by search_multi_cta_00_generate.py
 *
 * Make changes there and run in this directory:
 *
 * > python search_multi_cta_00_generate.py
 *
 */

#include "search_multi_cta_inst.cuh"
#include "sample_filter_utils.cuh"

#define COMMA ,

namespace cuvs::neighbors::cagra::detail::multi_cta_search {
instantiate_kernel_selection(
  int8_t, uint32_t, float, cuvs::neighbors::filtering::none_sample_filter);
instantiate_kernel_selection(
  int8_t, uint32_t, float, CagraSampleFilterWithQueryIdOffset<cuvs::neighbors::filtering::bitset_filter<uint32_t COMMA int64_t>>);

}  // namespace cuvs::neighbors::cagra::detail::multi_cta_search
